global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'inventory-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'inventory-api'

  - job_name: 'postgres-primary'
    static_configs:
      - targets: ['postgres-exporter-primary:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-primary'

  - job_name: 'postgres-replica'
    static_configs:
      - targets: ['postgres-exporter-replica:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-replica'

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
